<?php

namespace common\models;

use common\components\Format;
use Yii;
use yii\helpers\Url;

/**
 * This is the model class for table "blog".
 *
 * @property string $id
 * @property string $title
 * @property string $description
 * @property string $content
 * @property string $thumbnail
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $viewed_cnt
 * @property integer $status
 * @property string $slug
 * @property string $folder
 */
class Blog extends \yii\db\ActiveRecord
{
    const STATUS_ACTIVE = 1;
    const STATUS_DISABLE = 0;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'blog';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'description','thumbnail','content'], 'required',"message"=>"{attribute} không được để trống."],
            [['content'], 'string'],
            [['created_at', 'updated_at', 'viewed_cnt', 'status'], 'integer'],
            [['title'], 'string', 'max' => 300],
            [['description'], 'string', 'max' => 500],
            [['thumbnail'], 'string', 'max' => 255],
            [['folder'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Tiêu đề',
            'description' => 'Mô tả',
            'content' => 'Nội Dung',
            'thumbnail' => 'Ảnh đại diện',
            'created_at' => 'Tạo lúc',
            'updated_at' => 'Cập nhật cuối',
            'viewed_cnt' => 'lượt xem',
            'status' => 'Trạng thái',
            'slug' => 'Slug',
            'folder' => '',
        ];
    }
    private function getFolderPath(){
        return "/blogs/".time();
    }

    public function __construct($config = [])
    {
        parent::__construct($config); // TODO: Change the autogenerated stub
        if((is_null($this->folder) || empty($this->folder) )){
            $this->folder = $this->getFolderPath();
        }
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        if((is_null($this->folder) || empty($this->folder) )){
            $this->folder = $this->getFolderPath();
        }
    }


    public function beforeSave($insert)
    {
        if((is_null($this->slug) || empty($this->slug) )){
            $this->slug = Format::slug__filter($this->title);
        }
        if((is_null($this->created_at) || empty($this->created_at) )){
            $this->created_at = time();
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


    public function getViewUrl(){
        return Url::to(['blog/view','id'=>$this->id,'slug'=>$this->slug]);
    }
    public function getThumbnailUrl(){
        if(strpos($this->thumbnail,"http")===0){
            return $this->thumbnail;
        }
        return Yii::$app->request->baseUrl.$this->thumbnail;
    }
}
